### ISSUE TITLE
"Glock" typo

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Metlino#13]
![image](https://user-images.githubusercontent.com/720864/56094255-f36c9c00-5f04-11e9-9ff9-928efc653ade.png)

**Comment by sbourdeauducq** [comment]
Problem still present on v1.0rc4.
![image](https://user-images.githubusercontent.com/720864/57977025-ed486e80-7a20-11e9-88a9-59bbb57b1cdb.png)

**Comment by gkasprow** [comment]
true. fixed.
