### ISSUE TITLE
MCH Fabric D and E need at least 1 harness connector in the schematics

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/Metlino#16]
Right now there are many errors caused by this, signals are not recognised as part of the harness.

Could possibly affect other harnesses in the project also.

ed: Placing harness connector solved problems in the same sheet, not in the whole document.

**Comment by gkasprow** [comment]
not all signals are routed to FPGA.
I would simply remove the fabric E since we cannot ensure connectivity for all Sayma slots

**Comment by marmeladapk** [comment]
Yes, but the point is, that signals are to in the harness and thus are not connected accross schematics:

![Zrzut ekranu z 2019-04-26 10 28 59](https://user-images.githubusercontent.com/24512604/56794319-30426800-680e-11e9-89a0-376d5d0ab916.png)

**Comment by gkasprow** [comment]
that's strange. Do you have a harness file with the definition? It's required.
There are 2 ways of defining harness. Either you draw harness connector and the file is generated automatically or you define the harness in the file and use nets to keep connectivity. In the second case, the harness entry in the file is not generated automatically.

**Comment by marmeladapk** [comment]
I compiled the project straight from the repository. Perhaps some files are missing and weren't created automatically?

**Comment by marmeladapk** [comment]
WR_I2C_CTRL on MCH_FPGA_BANKS_64_65.schdoc for example doesn't register all signals MAIN_DCXO_OE, SCL, SDA are not shown as part of the harness.

**Comment by marmeladapk** [comment]
On AD17 and higher it is registered correctly.
