### ISSUE TITLE
DNP check

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/Metlino#28]
Compared with Xpedition schematics and with AMC

- DNP IC1
- DNP R40
- DNP IC14, MOD1, L8, C573, C571, C575, C577
- In Si5324_CDR_WR_oscillators no part is marked as dnp
- Same in DDMTD.schdoc
- Metlino_CLK_distribution - C326 and R352 are DNPed the other way around as in xpedition schematics

**Comment by gkasprow** [comment]
we will most likely get the clock from front panel input.

**Comment by marmeladapk** [comment]
- In Si5324_CDR_DCXO_oscillators still no part is marked as dnp

**Comment by marmeladapk** [comment]
IC14 and R141 are still not marked as DNP, but they seem to be mutually exclusive.

**Comment by gkasprow** [comment]
@marmeladapk R141 is for SDRAM VREF generation. IC14 is JTAG mux. Are you sure about these designators?
