### ISSUE TITLE
CLK_200MHz must reach Quad 228

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Metlino#35]
This clock is required for GTH Ethernet.
Currently it is placed in Quad 225 and cannot be properly routed.
We shouldn't need CDR_CLK_CLEAN2 so it can take its place.

**Comment by gkasprow** [comment]
I connected it to bank 226 instead of the UFL connectors so now can reach all banks.
the UFLs were connected to bank 225.
