### ISSUE TITLE
stop calling everything "WR"

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Metlino#38]
The Si5324 has nothing to do with White Rabbit.
![image](https://user-images.githubusercontent.com/720864/57976940-24b61b80-7a1f-11e9-8685-d498226cf639.png)

What about calling this (Si5324, DCXOs, DDMTD flip-flops, clock switches) the "central PLL" or the "central clocking subsystem"?

**Comment by sbourdeauducq** [comment]
Also here:
![image](https://user-images.githubusercontent.com/720864/57977068-5bd9fc00-7a22-11e9-96ab-c4800966946b.png)
Why is that a "WR" reference clock?
By the way, for clocks to be usable for DRTIO they need to go to transceiver clock inputs, GC pins cannot clock the transceivers well and can only be used to clock local RTIO peripherals. I am not sure what the use case is for this clock, and I don't know if this is a problem or not.

**Comment by hartytp** [comment]
Yes we should stop calling things wr as there is much more to the wr stack than a ddmtd pll. I don’t want to bikeshed terminology and will be happy with anything sensible and consistently applied.

**Comment by hartytp** [comment]
Was that ref the ddmtd pll reference when Metlino is used as the drtio master?

**Comment by sbourdeauducq** [comment]
Why do we need DDMTD when it's used as the master?

**Comment by hartytp** [comment]
True if you won’t use the DCXO at all then it’s not needed. On Kasli we’d want it to provide a nice clean clock to the EEMs but Metlino doesn’t have that requirement

**Comment by gkasprow** [comment]
OK, now I call this harness Clocking_CTRL and removed "WR" from signal names.
