### ISSUE TITLE
position of GC pins on VHDCI connector

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Metlino#39]
The VHDCI connector is supposed to be used with the VHDCI carrier, but for this purpose the location of GC pins does not seem to match.
For example, pins 1/35 of the VHDCI0 connector do not go to a GC pin of the Ultrascale FPGA on Metlino, but connect to bit 0 of EEM0 on the VHDCI carrier, which is used as a clock signal.

**Comment by gkasprow** [comment]
fixed. Now pins 1/35, 2/36, 20/54, 21/55 go to GC
![obraz](https://user-images.githubusercontent.com/4325054/57985313-3ec71c80-7a66-11e9-91ed-810275c50fa2.png)

**Comment by sbourdeauducq** [comment]
On 1.0rc5, FPGA pin of EEM bit0 for...
EEM0: D25/E25
EEM1: C22/C21
EEM2: A25/B25
EEM3: B26/C26
EEM4: W24/W23
....
So far only EEM0 and EEM4 are correct (go to GC pins). Or am I missing out something?
