### ISSUE TITLE
PCB DRC

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/Metlino#43]
Solder mask sliver constraint (IC4)
![drc_1_soldermask](https://user-images.githubusercontent.com/24512604/58158637-1cf2b300-7c7b-11e9-8448-b68e58a98195.PNG)

Rules:
- Disable silk to silk clearance constraint?
- Shouldn't minimum annular ring be 0,1mm?
- Add rule about matching length within all differential pair to say 2mm?
- Shouldn MCH_FABRIC_D signals be also length matched (don't know if they are matched in backplane)?

**Comment by gkasprow** [comment]
we don't care about GTH links length matching.
Altium calculates annular ring in a strange way. 0.1/0.3mm vias generate errors when the rule is set to more than 50um.
