### ISSUE TITLE
PCB and schematics are not synchronized

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/Metlino#44]

**Comment by gkasprow** [comment]
I've just checked. The PCB and schematics are synchronized. repo is up-to-date.
Here is direct Dropbox link https://www.dropbox.com/sh/6qw8ilrs1y406mt/AAAMVxfN1-PtRVFdapyhWw5na?dl=0

**Comment by marmeladapk** [comment]
@gkasprow I cloned a fresh repo to double check. I checked with AD 19.1.5. It seems that this may be caused by mismatch between ports and sheet entries, that's visible in compilation errors.

ed:And of course after I fixed Si5324 sheet name to the one in the project file.
