### ISSUE TITLE
Metlino v1.0 schematic review

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Metlino#5]
I published schematics. Still not decided what to do with fabric E, so ignore Bank64 connectivity with Fabric E signals. We will probably use 24pairs of Bank64, supplied from 2.5V to support full  E Fabric.

**Comment by hartytp** [comment]
Maybe too late to change this now, but is it worth considering replacing the VHDCI connectors with FMCs to give added flexibility. Users can always combine with an FMC->VHDCI adapter to break out to VHDCI.

Also, if the FP SMAs are too tight then let's replace with MMCXs or similar.

**Comment by hartytp** [comment]
Clock distribution page: 
- double check capacitors on the LT3045, including effects of bias voltage. NB IIRC the reference design wants a 10uF output capacitance
- why are there DNPd capacitors on the ADCLK948 Q1 outputs, when nothing connects to these outputs?

clock recovery page:
- rename to clock recovery, not SI5324_clk_recovery
- @marmeladapk once we finalize Sayma_AMC, please can you ensure that the clock recover is identical for Metlino? There are few small fixes we need to apply to Sayma, so we should make sure they get applied to the MCH as well
- @WeiDaZhang can you check that you are happy with the Metlino WR FPGA connections, please? You can find the schematic in the releases section of this project.
- @gkasprow is it possible to get an image of what the board + FP will look like (same for Sayma_AMC)?

Other than that, all the parts of the design that I feel qualified look good to me.

**Comment by gkasprow** [comment]
@sinara-hw/wut we don't have that much space to place FMC connectors instead of VHDCI.
We have one FMC but it is faced to backplane.

**Comment by hartytp** [comment]
> @sinara-hw/wut we don't have that much space to place FMC connectors instead of VHDCI.

ACK, I thought that might be the case. In that case don't worry about it.
