### ISSUE TITLE
Two holes close to each other

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/Metlino#52]
![holes](https://user-images.githubusercontent.com/24512604/58320327-b35dda80-7e1b-11e9-862c-7d8bb82ee73b.PNG)

**Comment by gkasprow** [comment]
why too close?

**Comment by marmeladapk** [comment]
Won't standoff interfere with whatever is supposed to go through the second hole and its nut?

**Comment by gkasprow** [comment]
we would use one or another.
