### ISSUE TITLE
PI analysis after optimization

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Metlino#58]
12V rail. Drop is mainly on MOSFETs.
![obraz](https://user-images.githubusercontent.com/4325054/60411754-89dc5f80-9bce-11e9-985c-92f966f3c1c3.png)
in one place the current density is high on the bottom layer. But we cannot do much. Via currents are fine.
![obraz](https://user-images.githubusercontent.com/4325054/60411764-93fe5e00-9bce-11e9-9de0-fc8d2616bc08.png)

**Comment by gkasprow** [comment]
1V rail
![obraz](https://user-images.githubusercontent.com/4325054/60411901-4f26f700-9bcf-11e9-9969-2a9b622707dd.png)
![obraz](https://user-images.githubusercontent.com/4325054/60411909-577f3200-9bcf-11e9-9d64-c9abcadd7ed5.png)

**Comment by gkasprow** [comment]
1V5 rail. The DC drop includes also 1V2 LDO so it is fine.
![obraz](https://user-images.githubusercontent.com/4325054/60411957-84cbe000-9bcf-11e9-8631-3b3a27c18ffa.png)
![obraz](https://user-images.githubusercontent.com/4325054/60411958-89909400-9bcf-11e9-9d79-3c9fd8e42a3e.png)

**Comment by gkasprow** [comment]
1V8
![obraz](https://user-images.githubusercontent.com/4325054/60411981-b2188e00-9bcf-11e9-820f-fd1a04177aa7.png)
![obraz](https://user-images.githubusercontent.com/4325054/60411984-b6dd4200-9bcf-11e9-9c54-a0eaae501758.png)

**Comment by gkasprow** [comment]
3V3 rail. Current density is slightly too high, but on the top layer polygon, so it's fine.
![obraz](https://user-images.githubusercontent.com/4325054/60412011-decca580-9bcf-11e9-9f74-b9a677a2d392.png)
![obraz](https://user-images.githubusercontent.com/4325054/60412016-e2f8c300-9bcf-11e9-971d-0bac5b7d9e04.png)

**Comment by gkasprow** [comment]
VCCINT. Note that the drop includes the coil DCR. In our case the voltage is stabilized under the FPGA.
Current density is high but we cannot really do much with it. It is dominated by buck chip to inductor connection.
![obraz](https://user-images.githubusercontent.com/4325054/60412103-2f440300-9bd0-11e9-8a37-ee24fb356491.png)
![obraz](https://user-images.githubusercontent.com/4325054/60412112-34a14d80-9bd0-11e9-8377-b6f04eb54cb8.png)

**Comment by gkasprow** [comment]
5V0 rail. It is used to supply 3V3 to clocking circuit via LDO. Simulation assumes that 3.3V LDO was shorted and includes 5V buck coil.
![obraz](https://user-images.githubusercontent.com/4325054/60412212-99f53e80-9bd0-11e9-80d1-64debcc73272.png)
![obraz](https://user-images.githubusercontent.com/4325054/60412221-9feb1f80-9bd0-11e9-9a43-149b46fc72aa.png)

**Comment by gkasprow** [comment]
P3V3MP
![obraz](https://user-images.githubusercontent.com/4325054/60412276-c8731980-9bd0-11e9-97c8-56379b2f5928.png)
![obraz](https://user-images.githubusercontent.com/4325054/60412283-cc06a080-9bd0-11e9-9ae2-a803132edb35.png)

**Comment by jbqubit** [comment]
Thanks @gkasprow!
