### ISSUE TITLE
Si analysis

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Metlino#59]
All simulations were performed using Hyperlynx VX2.3
Eye diagram @12Gbit 64/66 before optimization of the edge connector vias and before removing NFPs :
![obraz](https://user-images.githubusercontent.com/4325054/60416466-2f4aff80-9bde-11e9-9e1b-9a5d0bff91e9.png)

**Comment by gkasprow** [comment]
With NFPs removed and anti-pads increased
red - 2mm anti-pads
light blue - 1.6mm anti-pads
![obraz](https://user-images.githubusercontent.com/4325054/60416573-7638f500-9bde-11e9-86a2-4d57c0a5a295.png)

**Comment by gkasprow** [comment]
Eye diagram for Tx lanes after heavy optimization. There are additional vias and couplig caps
![obraz](https://user-images.githubusercontent.com/4325054/60462199-f5631300-9c48-11e9-80d3-b44aaf8d74fd.png)

**Comment by gkasprow** [comment]
SFP loopback test with  SFP cage SI model and GTX Rx/Tx. Settings at 12Gbit/s, 64/66
![obraz](https://user-images.githubusercontent.com/4325054/60482945-bad29800-9c93-11e9-8030-381a7fe2bdc3.png)
![obraz](https://user-images.githubusercontent.com/4325054/60482999-f79e8f00-9c93-11e9-8cc7-14a6abc168fa.png)

**Comment by gkasprow** [comment]
SiDDR test after optimization finally passes for 1.066GT/s speed.
The detailed report is [here](https://www.dropbox.com/s/k3h3jbyh6trdmn2/DDR_Results_Jul-4-2019_8h-15m.zip?dl=0)

**Comment by gkasprow** [comment]
[here](url)

**Comment by jordens** [comment]
The trace in https://github.com/sinara-hw/Metlino/issues/59#issuecomment-507141566 looks bad/weird. The difference hovers around 0 for half the UI. Was that an intermediate result or the final one?

**Comment by gkasprow** [comment]
It was an intermediate TDR result. The eye diagram looks much better - similar to the last one. The problem is with 0.6mm connector vias because their impedance cannot really be matched and will always be 30Ohm in the best case.
