### ISSUE TITLE
BOM verification

### ISSUE THREAD

**Issue by atcher0** [sinara-hw/Metlino#6]
BOM: https://octopart.com/bom-tool/VRV8plDm

Elements out of stock:
- 16251701301000 (Conn Board to Board PL 170 POS 1.5mm Solder RA Thru-Hole) - J13
- TSX-3225 25.0000MF10Z-AC (25 MHz ±10 ppm 18 pF -20 to +85°C Surface Mount Crystal Unit) - Q4

Elements with low avability / near end of life:
- J01151A0921 (Sma Angle Receptacle Pcb (f) 50 Ohm) - J1-J3
- FTS-114-02-L-DV-A (Conn Unshrouded Header HDR 28 POS 1.27mm Solder ST SMD Tube) - J4
- 16241701301000 (Right Angle Male Edge Connector; Through Hole Mount; 170 Way; 1 Row; 1.5mm Pitch) - J12

Additionally, problems from Sayma AMC (sinara-hw/Sayma_AMC#9) apply here.
@gkasprow

**Comment by gkasprow** [comment]
8Y-25.000MAAJ-T is again available.
J12/J13 is ordered directly from MFG
