### ISSUE TITLE
Si549 populated with LVDS not CMOS

### ISSUE THREAD

**Issue by jbqubit** [sinara-hw/Metlino#61]
> I got info that some of them had been stuffed with LVDS 
>version of Si549 due to CMOS version not being available in 
>that quantity at the time of order

It's unclear to me the implications of this change. @gkasprow ? Regardless, all Metlino should be stuffed identically to minimize board-to-board variation.

**Comment by gkasprow** [comment]
Sure, providing that the oscillators are available. AFAIK they are software-compatible.

**Comment by jbqubit** [comment]
@marmeladapk Have they been ordered?

**Comment by jbqubit** [comment]
@gkasprow @marmeladapk Can this be closed?

**Comment by marmeladapk** [comment]
Let's leave it open and close when they all have the same version of Si549.

**Comment by sbourdeauducq** [comment]
The LVDS/CMOS capacitor selection is also wrong on some boards.

**Comment by jbqubit** [comment]
What is s/n of board on which you see the problem?

**Comment by marmeladapk** [comment]
@jbqubit See https://github.com/sinara-hw/Metlino/wiki/Prototype-reworks

All boards have capacitors mounted for CMOS version.

We plan to switch all boards to LVDS.

**Comment by marmeladapk** [comment]
All boards now have LVDS version of Si549. Now I just need to find a moment to swap all capacitors and resistors to LVDS variant.

**Comment by marmeladapk** [comment]
All boards have LVDS RC variant now.
