### ISSUE TITLE
SDRAM REFIN is missing ground connection

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/Metlino#63]
Metlino:
![Zrzut ekranu z 2019-12-20 10 21 43](https://user-images.githubusercontent.com/24512604/71244359-9c7c5980-2312-11ea-96a8-d0f2038c81bd.png)

Sayma:
![Zrzut ekranu z 2019-12-20 10 22 08](https://user-images.githubusercontent.com/24512604/71244364-9f774a00-2312-11ea-8f71-4a60bb1e45fe.png)

**Comment by marmeladapk** [comment]
Adding solder blob fixes SDRAM init and ARTIQ tests.

**Comment by gkasprow** [comment]
ah, missing GND!

**Comment by filipswit** [comment]
fixed in v1.2
