### ISSUE TITLE
Components too close to the board edge

### ISSUE THREAD

**Issue by kaolpr** [sinara-hw/Metlino#66]
Power supply status LEDs, as well as their current setting resistors, are placed too close to the board edge. AMC specification requires at least 1.7mm, whereas diodes are placed as close as 0.988 mm.

Unfortunately, this is not only matter of standard complience. Too low distance causes components to be damaged by crate rails. Below is a photo of LEDs stripped off while sliding module into the crate.

![image](https://user-images.githubusercontent.com/9166701/72908640-1353aa80-3d36-11ea-90aa-6a313a6e3730.png)

**Comment by gkasprow** [comment]
let's move them by 0.5mm using hot air gun.

**Comment by filipswit** [comment]
Components moved to be min. 1.74mm away
