### ISSUE TITLE
Si5324 I2C low level is too high

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/Metlino#68]
Si5324 seems not to be able to properly pull SDA low. Tested with FPGA and with MMC talking to Si5324. Other than that Si5324 is reacting properly.

We modified pullup resistors on both sides to 10k. It didn't help.

Screenshot on CPU pullup resistors:

![tek00013](https://user-images.githubusercontent.com/24512604/73672041-76393000-46ac-11ea-8daf-5c893cc31298.png)

Screenshot on I2CMUX4 bus:

![tek00012](https://user-images.githubusercontent.com/24512604/73672098-936dfe80-46ac-11ea-8d67-1b19309ec743.png)

**Comment by gkasprow** [comment]
It looks like one of the ICs was switched to fast mode (push-pull IOs) or MMC has wrong IO mode ( push-pull enabled )

**Comment by gkasprow** [comment]
observe SDA before and after the I2C mux

**Comment by kaolpr** [comment]
> Si5324 seems not to be able to properly pull SDA low. Tested with FPGA and with MMC talking to Si5324. Other than that Si5324 is reacting properly.
> 
> We modified pullup resistors on both sides to 10k. It didn't help.
> 
> Screenshot on CPU pullup resistors:
> 
> ![tek00013](https://user-images.githubusercontent.com/24512604/73672041-76393000-46ac-11ea-8daf-5c893cc31298.png)
> 
> Screenshot on I2CMUX4 bus:
> 
> ![tek00012](https://user-images.githubusercontent.com/24512604/73672098-936dfe80-46ac-11ea-8d67-1b19309ec743.png)

@gkasprow These are signals before mux (CPU pullup resistors) and after (I2CMUX4).

**Comment by marmeladapk** [comment]
I shorted FPGA bus with Si5324 bus, ACK is still >1V. Both muxes are held in reset.

**Comment by marmeladapk** [comment]
Just as a precaution I removed muxes and left only 10kOhm pullup (one per line). Still the same.

Hmm, low level on SCL is quite high - around 800mV.
![image](https://user-images.githubusercontent.com/24512604/73758707-47ce5a00-476b-11ea-9d9f-d0af66ce64b8.png)

**Comment by marmeladapk** [comment]
Found it!

FPGA I2C bus is also connected to the CPU (LPC1776).

CPU was configured differently than on Sayma: `IOCON_MODE_INACT` on Metlino, `IOCON_OPENDRAIN_EN` in Sayma. After changing this, Si5324 works in ARTIQ as @sbourdeauducq tested.
