### ISSUE TITLE
photos of Metlino

### ISSUE THREAD

**Issue by jbqubit** [sinara-hw/Metlino#69]
Please post photos of Metlino front side, back side, front end-on, back end-on. 

https://github.com/sinara-hw/Metlino/issues/67#issuecomment-581549618

**Comment by kaolpr** [comment]
### 1907180PW0006A0101

![IMG_20200205_152458061_HDR](https://user-images.githubusercontent.com/9166701/75143921-4521ad80-56f6-11ea-8f9d-0d449002224b.jpg)
![IMG_20200205_152421195_HDR](https://user-images.githubusercontent.com/9166701/75143931-4a7ef800-56f6-11ea-8c52-8961a1881ed5.jpg)
![IMG_20200205_152443628_HDR](https://user-images.githubusercontent.com/9166701/75143934-4ce15200-56f6-11ea-9251-3ca0bb779242.jpg)
![IMG_20200205_152431032](https://user-images.githubusercontent.com/9166701/75143939-4e127f00-56f6-11ea-8ce1-4a2f35f00533.jpg)

### 1907180PW0006A0102

![IMG_20200205_152153814_HDR](https://user-images.githubusercontent.com/9166701/75143971-5f5b8b80-56f6-11ea-937c-b51ee12247c7.jpg)
![IMG_20200205_152053863_HDR](https://user-images.githubusercontent.com/9166701/75143974-61bde580-56f6-11ea-9d7d-f761a6f82b4e.jpg)
![IMG_20200205_152141953_HDR](https://user-images.githubusercontent.com/9166701/75143979-6387a900-56f6-11ea-8022-7b94acb6e8e4.jpg)
![IMG_20200205_152114374_HDR](https://user-images.githubusercontent.com/9166701/75143982-65516c80-56f6-11ea-8807-30bf874ff2b0.jpg)

### 1907180PW0006A0103

![IMG_20200205_152301268_HDR](https://user-images.githubusercontent.com/9166701/75143999-6e423e00-56f6-11ea-8163-d7e58e64fe33.jpg)
![IMG_20200205_152216396_HDR](https://user-images.githubusercontent.com/9166701/75144003-6f736b00-56f6-11ea-869a-26ad252baa58.jpg)
![IMG_20200205_152245407_HDR](https://user-images.githubusercontent.com/9166701/75144007-713d2e80-56f6-11ea-9374-d685005b5bce.jpg)
![IMG_20200205_152231432_HDR](https://user-images.githubusercontent.com/9166701/75144014-7306f200-56f6-11ea-8a8a-324645b83c59.jpg)

### 1907180PW0006A0104

![IMG_20200205_152355265_HDR](https://user-images.githubusercontent.com/9166701/75144037-7b5f2d00-56f6-11ea-85c4-28c100b9417c.jpg)
![IMG_20200205_152328530_HDR](https://user-images.githubusercontent.com/9166701/75144043-7d28f080-56f6-11ea-87e9-18197dfdbadc.jpg)
![IMG_20200205_152344324_HDR](https://user-images.githubusercontent.com/9166701/75144045-7ef2b400-56f6-11ea-8a4e-4e85ae49a39a.jpg)
![IMG_20200205_152335605](https://user-images.githubusercontent.com/9166701/75144048-8023e100-56f6-11ea-87b4-3ddc6b965161.jpg)

### 1907180PW0006A0105

![IMG_20200205_152624676](https://user-images.githubusercontent.com/9166701/75144069-89ad4900-56f6-11ea-9612-7103d3b9a4e0.jpg)
![IMG_20200205_152540253_HDR](https://user-images.githubusercontent.com/9166701/75144101-96ca3800-56f6-11ea-9b75-f7a936fa10c9.jpg)
![IMG_20200205_152614863_HDR](https://user-images.githubusercontent.com/9166701/75144105-9893fb80-56f6-11ea-8e14-261c2ceb629c.jpg)
![IMG_20200205_152548418_HDR](https://user-images.githubusercontent.com/9166701/75144106-9a5dbf00-56f6-11ea-83cf-fb34db2807bf.jpg)

**Comment by jbqubit** [comment]
At long last! Thanks.

**Comment by akaminska** [comment]
Unpopulated PCBs
![IMG_20200324_134540](https://user-images.githubusercontent.com/45766037/78688412-86ac9780-78f5-11ea-85d5-c04c248facda.jpg)

**Comment by jbqubit** [comment]
Thank you for the PCB photos. 

Do you also have Metlino photo with front panel installed? With riser card connecting to NAT MCH?

**Comment by akaminska** [comment]
@kaolpr is preparing a photostory on how to integrate Metlino with MCH and attach panel right now. Should appear soon.

**Comment by akaminska** [comment]
![IMG_20200415_173446658](https://user-images.githubusercontent.com/45766037/79466874-71bebb00-7ffd-11ea-92d7-a72a4652e961.jpg)
![IMG_20200415_173727040](https://user-images.githubusercontent.com/45766037/79467015-99ae1e80-7ffd-11ea-8207-642c3e6d6d4f.jpg)
![IMG_20200415_121124272](https://user-images.githubusercontent.com/45766037/79467060-a6cb0d80-7ffd-11ea-98c6-936e2e2d408f.jpg)

**Comment by jbqubit** [comment]
Thanks!!
