### ISSUE TITLE
No P3V3 MP on Metlino #105

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/Metlino#70]
IC41 was dead. After swapping for a new one it works again.

**Comment by gkasprow** [comment]
IC41 is Ethernet PHY, not supplied from P3V3MP

**Comment by gkasprow** [comment]
@marmeladapk what is IC41? Why it failed?

**Comment by marmeladapk** [comment]
@gkasprow I was looking at Sayma schematics not at Metlino. IC7 was dead - buck converter that supplied P3V3_MP. I have no idea why it failed, it had all correct voltages supplied to it and resoldering didn't help.

**Comment by gkasprow** [comment]
It could get too high input voltage or reverse biasing

**Comment by gkasprow** [comment]
I assume you meant IC18.

**Comment by gkasprow** [comment]
IC7 is USB controller on Sayma AMC

**Comment by marmeladapk** [comment]
We're talking about Metlino.
